package enums

const (
	RECOMMEND_TYPE_FOR_CUSTOM       = 0
	RECOMMEND_TYPE_FOR_MY_SUBSCRIBE = 1
	RECOMMEND_TYPE_FOR_HOT          = 2
	RECOMMEND_TYPE_FOR_UPGRADE      = 3
	RECOMMEND_TYPE_FOR_AUTHOR       = 4
	RECOMMEND_TYPE_FOR_CATEGORY     = 5
)
